# Run this command to start the database:
# docker-compose up --build
version: "3"
services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - 8013:5432
    restart: always
    environment:
      - POSTGRES_DB=case_study
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword